version: '2.1'

volumes:
  kong_data: {}

networks:
  kong-net:
services:
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    links:
      - kong-database:kong-database
    networks:
      - kong-net
    restart: on-failure
  kong-migrations-up:
    image: kong:latest
    command: kong migrations up
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    links:
      - kong-database:kong-database
    networks:
      - kong-net
    restart: on-failure
  kong:
    image: kong:latest
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      LETSENCRYPT_HOST: kong.ci.aws.labshare.org
      LETSENCRYPT_EMAIL: build@labshare.org
      VIRTUAL_HOST: kong.ci.aws.labshare.org
      VIRTUAL_PORT: 8000
      HOST: 0.0.0.0
      UPSTREAM: kong.ci.aws.labshare.org-service
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
  kong-database:
    image: cassandra:3
    ports:
      - 9042:9042
    expose:
      - 9042
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5